### ISSUE TITLE
Mac OS make test problems.. su: not found

### ISSUE THREAD

**Issue by saksua** [evilsocket/arminject#10]
I run on Mac OSX, target: BlueStack emulator, problems: below. Please check ...
# make test

make[1]: Entering directory `/Users/xxx/Downloads/arminject-master'
Compile++ thumb  : hook <= main.cpp
Compile++ thumb  : hook <= hook.cpp
Compile++ thumb  : hook <= report.cpp
Compile++ thumb  : hook <= io.cpp
SharedLibrary  : libhook.so
Install        : libhook.so => libs/armeabi-v7a/libhook.so
Compile++ thumb  : injector <= main.cpp
Executable     : injector
Install        : injector => libs/armeabi-v7a/injector
make[1]: Leaving directory`/Users/xxx/Downloads/arminject-master'
python test.py
@ Pushing files to /data/local/tmp ...
@ Starting com.android.chrome/com.google.android.apps.chrome.Main ...
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    pid = adb.start_activity( process, activity )
  File "/Users/xxx/Downloads/arminject-master/pyadb/adb.py", line 63, in start_activity
    return self.get_pid( proc )
  File "/Users/xxx/Downloads/arminject-master/pyadb/adb.py", line 57, in get_pid
    return int( self.sudo( "pidof %s" % proc ).strip() )
ValueError: invalid literal for int() with base 10: '/system/bin/sh: su: not found'
make: **\* [test] Error 1

**Comment by fabrandolini** [comment]
Same problem here!
MAC OS X 10.10.5
Any idea about this?

**Comment by evilsocket** [comment]
You need a rooted phone.

```
/system/bin/sh: su: not found
```
