### ISSUE TITLE
"ADB binary not found in PATH"

### ISSUE THREAD

**Issue by tribalart** [evilsocket/arminject#3]
hello, its probably not a issue , im sorry, but i dont know why i got this error : 

ruby 2.0.0p645 (2015-04-13) [i386-mingw32]

c:\arminject>adb devices
List of devices attached
20080411        device

c:\arminject>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

c:\arminject>make test
make.exe[1]: Entering directory `/c/arminject'

[armeabi-v7a] Cygwin         : Generating dependency file converter script
[armeabi-v7a] Compile++ thumb: hook <= main.cpp
[armeabi-v7a] Compile++ thumb: hook <= hook.cpp
[armeabi-v7a] Compile++ thumb: hook <= report.cpp
[armeabi-v7a] Compile++ thumb: hook <= io.cpp
[armeabi-v7a] SharedLibrary  : libhook.so
[armeabi-v7a] Install        : libhook.so => libs/armeabi-v7a/libhook.so
[armeabi-v7a] Compile++ thumb: injector <= main.cpp
[armeabi-v7a] Executable     : injector
[armeabi-v7a] Install        : injector => libs/armeabi-v7a/injector
make.exe[1]: Leaving directory `/c/arminject'
python test.py
'which' is not recognized as an internal or external command,
operable program or batch file.

[STDERR] :
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    adb = ADB()
  File "c:\arminject\pyadb\adb.py", line 34, in **init**
    raise "ADB binary not found in PATH."
TypeError: exceptions must be old-style classes or derived from BaseException, not str
make: **\* [test] Error 1

c:\arminject>

**Comment by mokhdzanifaeq** [comment]
pyadb is intended to be run on linux system. the missing **which** command is used to check for adb installation. you need to modify the pyadb scripts to run it on windows

**Comment by tribalart** [comment]
thanks you  :)
